# Short Url Redirects
[[redirects]]
  from = "/rick"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  status = 302

[[redirects]]
  from = "https://twitter.silverwood.dev/*"
  to = "https://twitter.com/silverwooddev"
  status = 302